### ISSUE TITLE
Can't push images with 4 levels of path

### ISSUE THREAD

**Issue by foggy-glasses** [ContainerSolutions/trow#86] opened 2020-04-17 13:57 UTC
I tagged an image as myregistry.mydomain.com/dt/platform/onprem/dashboard:04_2020. When I attempt to push this to myregistry-domain.com, I get a 404 not found error. Details below.

**Trow version: 0.2**
**Login and image listing**
```
masternode@masternode-VirtualBox:~/yml_files$ sudo docker login -u userone https://myregistry.mydomain.com/
Password:
WARNING! Your password will be stored unencrypted in /home/masternode/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
masternode@masternode-VirtualBox:~/yml_files$ sudo docker image ls myregistry.mydomain.com/dt/platform/onprem/dashboard:04_2020
REPOSITORY                                             TAG                 IMAGE ID            CREATED             SIZE
myregistry.mydomain.com/dt/platform/onprem/dashboard   04_2020             01a171b6c7fc        5 days ago          156MB

```
**Pushing the image to the registry**
```
masternode@masternode-VirtualBox:~/yml_files$ sudo docker push myregistry.mydomain.com/dt/platform/onprem/dashboard:04_2020
The push refers to repository [myregistry.mydomain.com/dt/platform/onprem/dashboard]
86e7ef159604: Preparing
7094a8a172b5: Preparing
d0f9dd2e3ff9: Preparing
e289c2a0087f: Preparing
fe6a7a3b3f27: Preparing
d0673244f7d4: Waiting
d8a33133e477: Waiting
error parsing HTTP 404 response body: json: cannot unmarshal string into Go value of type struct { Errors []errcode.Error }: "\"404 page not found\""

```

**Logs from the trow-set-0 pod**
```
_[WARN] Responding with 401 Unauthorized catcher.
_[ERROR] No matching routes for POST /v2/dt/platform/onprem/dashboard/blobs/uploads/.
_[ERROR] No matching routes for POST /v2/dt/platform/onprem/dashboard/blobs/uploads/.
_[WARN] Responding with 404 Not Found catcher.
_[ERROR] No matching routes for POST /v2/dt/platform/onprem/dashboard/blobs/uploads/.
_[WARN] Responding with 404 Not Found catcher.
_[WARN] Responding with 404 Not Found catcher.
_[ERROR] No matching routes for POST /v2/dt/platform/onprem/dashboard/blobs/uploads/.
_[WARN] Responding with 404 Not Found catcher.
_[ERROR] No matching routes for POST /v2/dt/platform/onprem/dashboard/blobs/uploads/.
_[WARN] Responding with 404 Not Found catcher.
```

**Logs from the nginx-pod**
```
10.244.1.1 - test2 [17/Apr/2020:13:46:58 +0000] "GET /login?account=userone&scope=repository%3Adt%2Fplatform%2Fonprem%2Fdashboard%3Apush%2Cpull&service=trow_registry HTTP/1.1" 200 298 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/5.3.0-46-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(linux\x5C))" 419 0.316 [test2-trow-svc-8000] [] 10.244.1.51:8000 326 0.316 200 de91998921064322cba89b6f486eab9b
10.244.1.1 - - [17/Apr/2020:13:46:58 +0000] "POST /v2/dt/platform/onprem/dashboard/blobs/uploads/ HTTP/1.1" 404 20 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/5.3.0-46-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(linux\x5C))" 670 0.041 [test2-trow-svc-8000] [] 10.244.1.51:8000 20 0.040 404 9583ca0702b079c18f3b9272398105c9
10.244.1.1 - - [17/Apr/2020:13:46:58 +0000] "POST /v2/dt/platform/onprem/dashboard/blobs/uploads/ HTTP/1.1" 404 20 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/5.3.0-46-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(linux\x5C))" 670 0.038 [test2-trow-svc-8000] [] 10.244.1.51:8000 20 0.036 404 0a6f124c7050a7507e50183e2ccd6b8c
10.244.1.1 - - [17/Apr/2020:13:46:58 +0000] "POST /v2/dt/platform/onprem/dashboard/blobs/uploads/ HTTP/1.1" 404 20 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/5.3.0-46-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(linux\x5C))" 670 0.037 [test2-trow-svc-8000] [] 10.244.1.51:8000 20 0.036 404 06ad5fe7249927de2cb087484f3e21ad
10.244.1.1 - - [17/Apr/2020:13:46:58 +0000] "POST /v2/dt/platform/onprem/dashboard/blobs/uploads/ HTTP/1.1" 404 20 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/5.3.0-46-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(linux\x5C))" 670 0.036 [test2-trow-svc-8000] [] 10.244.1.51:8000 20 0.032 404 fa3ce6635f4647c5693757166964dc06
10.244.1.1 - - [17/Apr/2020:13:46:58 +0000] "POST /v2/dt/platform/onprem/dashboard/blobs/uploads/ HTTP/1.1" 404 20 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b7f0 kernel/5.3.0-46-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(linux\x5C))" 670 0.042 [test2-trow-svc-8000] [] 10.244.1.51:8000 20 0.044 404 359e0790aafe5bdd63c2ee853961128a
```

Not sure if I'm missing something or if this is totally incorrect. I have an EKS cluster running off ECR platform where I tag images as such and it gets pushed without any issues. Of course, I do first create a repository in ECR with the same format before pushing in.

**Comment by amouat** [comment] 2020-04-17 14:53
The problem is that as things stand, trow doesn't support that level of nesting. If you rename the image to remove one level, it will push fine e.g if we remove `dt`:

```
docker push localhost:8000/platform/onprem/dashboard:04_2020         
The push refers to repository [localhost:8000/platform/onprem/dashboard]
6f23cf4d16de: Pushed 
531743b7098c: Pushed 
04_2020: digest: sha256:afea1c737cb0d6cf0769f0d9a05b10e078aaedb8acfe296b35c7d3964b92036a size: 719
```
(I'm just using a copy of the alpine image here).

Ideally, Trow would support an arbitrary level of nesting, but there are issues with how routing works in the underlying Rocket library. At any rate, the error message definitely needs to be improved, so I'll leave this issue open until that's fixed.

**Comment by foggy-glasses** [comment] 2020-04-18 03:28
Thanks! So this will support upto 3 levels. That's good to know as I can definitely work with that.

Perhaps you can mention this in the documentation?

**Comment by amouat** [comment] 2020-04-20 08:06
@foggy-glasses I'd rather fix it full stop to be honest. I'll have a thin :)

**Comment by amouat** [comment] 2020-04-20 17:00
Just pushed #89 that will allow 4 levels in repos. The code is horrible, and should really be refactored. This might need to wait until I move to a different framework however.

I'm going to take a look at trying to improve the error message (for 5 levels) before closing this.

**Comment by amouat** [comment] 2020-04-22 09:36
Added a better error message (which needed a bit of a hack, but such is) in #91

**Closed by amouat** 2020-04-22 09:36 UTC
