### ISSUE TITLE
Not able to pull images from trow-registry. "unexpected commit digest"

### ISSUE THREAD

**Issue by Christian-Rau** [ContainerSolutions/trow#228] opened 2021-01-19 17:36 UTC
I assume I must have missed the secret "cred" pod, so could someone please explain how to set the deployment API:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimistic-app
  namespace: notdefaultforsure
spec:
  selector:
    matchLabels:
      name: optimistic-backend
  template:
    metadata:
      labels:
        name: optimistic-backend
    spec:
      imagePulleSecrets:
        - name: trow-password   << what to add here?
      containers:
        - name: backend
          image: trow.optimistic.reg/simpleapp:latest
          ports:
            - containerPort: 80
```

I used the helm chart - but that's not ideal as I couldn´t figure out how to set a namespace. 
Edit: cleaned up a bit.

**Comment by amouat** [comment] 2021-01-20 15:30
So in the Helm chart you can explicitly set a username and password for the registry. If you don't do this, it should be configured with no password authentication. 

If there's no password, just remove the "imagePullSecrets" section.

 If there is a password, follow the Kubernetes docs on how to create the secret at https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/. It should be something like:
 
 ```
 kubectl create secret docker-registry regcred --docker-server=trow.optimistic.reg --docker-username=<your-name> --docker-password=<your-pword>
 ```
 
 Where the name and password are whatever you put in the Helm config.

**Comment by Christian-Rau** [comment] 2021-01-20 20:59
Thank you.. did that as well, 
I am able to pull and push from outside of the cluster. No problem at all.
read about containerd, and possible errors related to that, but with no luck.
According to the k3s docs I made a registries.yaml, with creds to trow.
This is the error I get, when deploy a pod:
"
Failed to pull image "trow.reg.com/image:k3s": rpc error: code = FailedPrecondition desc = failed to pull and unpack image "trow.reg.com/image": failed commit on ref "config-sha256:695e143792a2c7692076f30f705bbfcc8bb89bb312d32bc16837b032938ba37a": unexpected commit digest sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, expected sha256:695e143792a2c7692076f30f705bbfcc8bb89bb312d32bc16837b032938ba37a: failed precondition
"

**Comment by amouat** [comment] 2021-01-21 08:08
That's actually a bug I've been having problems recreating! Can you give more details on what you did to get that? What image you used, the version of kubernetes and containerd etc?

**Comment by Christian-Rau** [comment] 2021-01-21 09:06
Sure.
kubernetes v19.7
containerd v1.4.3
Trow image: docker.io/containersol/trow:0.3

this is the deployment section of the config:
`---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: web
spec:
  selector:
    matchLabels:
      name: web-backend
  template:
    metadata:
      labels:
        name: web-backend
    spec:
      containers:
        - name: backend
          image: trow.reg.com/mynginx:test
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---`

This is the helm values.yaml settings:
`
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: containersol/trow
imagePullSecrets: []
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  tls: 
  - hosts:
    - trow.reg.com
    secretName: myingress-cert
  hosts:
  - host: trow.reg.com
    paths:
    - /
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 8000
  type: ClusterIP
tolerations: []
trow:
  domain: trow.reg.com
  password: password
  user: user
  validatingWebhooks:
    enabled: false
volumeClaim:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
`

The config file I use to deploy the app works fine when using docker hub
`kubectl apply -f app-deploy.yml`

**Comment by Christian-Rau** [comment] 2021-01-21 09:20
I also checked to see of there should be some layer-cache issue in:
`${containerd folder}/io.containerd.content.v1.content/ingest`

But that is empty.

**Comment by kervel** [comment] 2021-02-19 12:32
i have the same problem on k3s (which is based on containerd). its rather easy to reproduce:

first i installed a local CA using cert-manager:

```shell
# install cert-manager 1.2.0
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml

# creating a local CA (letsencrypt won't work for localhost)
mkdir /tmp/ca.$$ && cd /tmp/ca.$$
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -subj "/CN=local_k3s" -days 3650 -reqexts v3_req -extensions v3_ca -out ca.crt
kubectl create secret tls ca-key-pair \
   --cert=ca.crt \
   --key=ca.key \
   --namespace=cert-manager


# lets make sure our computer trusts this CA!
sudo cp ca.crt /usr/local/share/ca-certificates/selfsigned-k3s.crt && sudo update-ca-certificates



# lets create a cluster issuer that will issue certificates using our newly created CA
cat << END | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-key-pair
END

```
then i restarted docker and k3s otherwise they would not accept the new certificate.
then i installed trow via helm:

```shell
kubectl create namespace trow

# let's create a SSL certificate for our container registry
cat << END  | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trow-kube-public
  namespace: trow
spec:
  secretName: trow-kube-public
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: trow.kube-public
  dnsNames:
  - trow.kube-public
END

# let's install trow
helm repo add trow https://trow.io
helm install trow trow/trow \
         --namespace trow \
         --create-namespace \
         --set 'trow.domain=trow.kube-public' \
         --set 'ingress.enabled=true' \
         --set 'ingress.hosts[0].host=trow.kube-public,ingress.hosts[0].paths={"/"}' \
         --set 'ingress.tls[0].hosts[0]=trow.kube-public' \
         --set 'ingress.tls[0].secretName=trow-kube-public' \
         --set trow.user=user --set trow.password=password
```

then i created imagepullsecrets and patched the default service account to use them
```shell
# let's fake a DNS entry!
MYIP=$(hostname -I | cut -d' ' -f1)
echo "$MYIP trow.kube-public" | sudo tee -a /etc/hosts

kubectl create secret docker-registry trow --docker-server=trow.kube-public \
     --docker-username=user --docker-password=password

kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "trow"}]}'

```

then i tried pushing an image and using it:

```shell
docker tag ubuntu:20.04 trow.kube-public/ubunt
docker run -it --rm --image trow.kube-public/ubunt -- bash
```

then i got exactly the same error with exactly the same hash (which is the hash of an empty file). in the logs i found:

```
 Trow is up and running!                                                                                                                                                                                                                                                                                                           │
│ _[WARN] Responding with 401 Unauthorized catcher.                                                                                                                                                                                                                                                                                 │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:da7391352a9bb76b292a568c066aa4c3cbae8d494e6a3c68e3c596d34f7c75f8.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:14428a6d4bcdba49a64127900a0691fb00a3f329aced25eb77e3b65646638f8d.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:2c2d948710f21ad82dce71743b1654b45acb5c059cf5c19da491582cef6f2601.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:f643c72bc25212974c16f3348b3a898b1ec1eb13ec1539e10a103e6e217eb2f1.                                                                                                                                                                                                     │
│ _[WARN] Responding with 401 Unauthorized catcher.                                                                                                                                                                                                                                                                                 │
│ _[WARN] Responding with 401 Unauthorized catcher.                                                                                                                                                                                                                                                                                 │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:2c2d948710f21ad82dce71743b1654b45acb5c059cf5c19da491582cef6f2601.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:14428a6d4bcdba49a64127900a0691fb00a3f329aced25eb77e3b65646638f8d.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:da7391352a9bb76b292a568c066aa4c3cbae8d494e6a3c68e3c596d34f7c75f8.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/ubunt/blobs/sha256:f643c72bc25212974c16f3348b3a898b1ec1eb13ec1539e10a103e6e217eb2f1.                                                                                                                                                                                                     │
│ _[ERROR] No matching routes for HEAD /v2/j/manifests/latest application/vnd.docker.distribution.manifest.v2+json.                                                                                                                                                                                                                 │
│ _[WARN] Responding with 401 Unauthorized catcher.                                                                                                                                                                                                                                                                                 │
│ _[ERROR] No matching routes for POST /login application/x-www-form-urlencoded; charset=utf-8.                                                                                                                                                                                                                                     │
│ _[WARN] Responding with 404 Not Found catcher.                                                                                                                                                                                                                                                                                    │
│ _[ERROR] No matching routes for HEAD /v2/j/manifests/latest application/vnd.docker.distribution.manifest.v2+json.                                                                                                                                                                                                                 │
│ _[WARN] Responding with 401 Unauthorized catcher.                                                                                                                                                                                                                                                                                 │
│ _[ERROR] No matching routes for POST /login application/x-www-form-urlencoded; charset=utf-8.                                                                                                                                                                                                                                     │
│ _[WARN] Responding with 404 Not Found catcher.                                                                                                                                                                                                                                                                                    │
```

**Comment by amouat** [comment] 2021-02-19 13:56
Thanks you @kervel ! I'll try to take a look at this in the middle of next week.

**Comment by amouat** [comment] 2021-02-28 15:27
I've made some progress on this. You might want to try a build from master and see what the current error is. It's been a big pain to reproduce as configuring a standalone containerd is weirdly difficult. I should see if I can get it running in a container :)

Part of the problem seems to have been that Trow wasn't setting the content-length header after a recent refactoring. I've fixed this, but then I started getting errors about the size being incorrect that I've not got to the bottom of. Possibly they are just red herrings caused by after effects of earlier tests.

There may still be an issue with authentication, but it wasn't working without authentication either, so I haven't investigated that part yet.

**Comment by amouat** [comment] 2021-03-03 11:57
I've just spent the morning retesting and things seem to be working, so it seems to have been entirely the missing content-length header. K3S can pull an image from Trow with and without authentication.

If you want to use this fix, you'll need to use an image built from the master branch e.g. `containersol/trow:2021-02-27-112-amd64` or even `latest`.

In the meantime I'll create a release and look at updating the helm chart.

**Comment by kervel** [comment] 2021-03-03 16:28
Great, thanks a lot !

greetings,
Frank

**Comment by amouat** [comment] 2021-03-04 09:42
Ok, the Helm chart should be updated.

If you get a chance to test again, please let me know. I'm going to close this for the minute as I think it at least fixes some of the problems.

**Closed by amouat** 2021-03-04 09:42 UTC

**Comment by kervel** [comment] 2021-03-10 15:05
confirming trow works now! thanks a lot.

**Comment by amouat** [comment] 2021-03-10 16:47
Good to know! Thanks for testing for me.
